### ISSUE TITLE
About Python versions

### ISSUE THREAD

**Issue by martinmanzo** [yunojuno/django-nps#8]
Hi, this package is exactly what I'm looking for. It looks great and simple to use.

What is preventing me to install it is the 3.7 Python requirement, what's the need of using only the newer version? I have no problem upgrading the version in my dev env, but in production that won't be very well welcomed. 

Why not being compatible with 3.5 and above?

Thanks!

**Comment by hugorodgerbrown** [comment]
Hi @martinmanzo thanks for the feedback. We dropped 3.6 and below as part of a sweep through all of our OSS Python projects to add type hints. 3.7 introduced [PEP 563: Postponed Evaluation of Annotations](https://docs.python.org/3/whatsnew/3.7.html#pep-563-postponed-evaluation-of-annotations), which made type hinting easier to implement in a future-proof (ish) way.

If you would like to use it, but want to use 3.5, you have two options: pin your dependency to the pre-3.7 version (0.6), or fork the project itself, and add the dependency from your own repo. Either will work.

This project isn't moving forward much - it does what it says, no more, so there's no requirement to keep updating it - a pinned dependency will work for a long time to come.

**Comment by martinmanzo** [comment]
Hi @hugorodgerbrown , thanks for the quick response.

I understand, it's cool. I'm gooing to use the 0.6 version until we update python.

Thanks!
